version: "2.2"

services:
  docker-janitor:
    image: docker-janitor:latest
    environment:
      - INTERVAL=6h
      - FRESHNESS=12h
      - CLEAR_IMAGES=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 50m
    cpus: 0.1 